### ISSUE TITLE
Fantasy Realms - Necromancer Issue

### ISSUE THREAD

**Issue by 88MatteoB** [fantasy-realms/fantasy-realms.github.io#3]
Hi,

During the scoring phase of many recent games, while We were following the scoring app, it often happened that, using the Necromancer effect, the player chosed, by mistake, a discard card he was not allowed to add since it was not an "Army, Leader, Wizard, or Beast" (or "Undead" if playing with the expansion). 

This last rule is clearly written on the card and also on the app but it's true that, to avoid that particular mistake, the app could put some constraint while choosing the extra 8th card (or 9th if the appropriate expansion mode is active).

wizkids.io/FRApp

Did you consider the possibility of putting, for example, a "Use" button on the Necromancer effect (which enables then to select only cards in the allowed suits) rather than allowing to choose freely an extra card?
Or was it intentionally designed like that to avoid, for example, any possible issue in case the Genie or Leprechaun are also in play?

Thank you for your feedback.
Bye.

Matteo

**Comment by jpraet** [comment]
This is mainly intended to be a scoring app, it does not aim to implement and enforce all the rules in the game. Enforcing the order of these extra card draws when Necromancer+Genie+Leprechaun are in play, and preventing from discarding a card that you already used to draw a card, ... introduces way more complexity into the app.

That being said, there is some limited logic that happens when Necromancer is in play, e.g. if you have 7 cards in hand, and none are valid Necromancer candidates, it won't let you add the Necromancer as 8th card. Similarly, if you have Necromancer + 6 non-valid candidates in hand, it will only let you add a valid candidate as the 8th card. But if you already have a valid candidate in hand, it doesn't care. That is also done in order to allow flexibility in introducing your cards into the scoring app in any order you prefer.

**Comment by 88MatteoB** [comment]
Yep, I've noticed that detail and I imagined that it was a choice of design to favour the flexibility.
After your feedback I'm now convinced that it has been adopted the best approach.
Thank you very much for your brilliant support for all 3 tickets.
